modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="wildfarmcraft"
version="1.0.0"
displayName="WildFarmCraft"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Windows, MCreator"

[[dependencies.wildfarmcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




